server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://116.62.13.6:3306/wall?serverTimezone=GMT%2B8
    username: dqdLZ
    password: foreverFootball
  redis:
    port: 6379
    password: Justmyself957
    host: 116.62.13.6
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000
      shutdown-timeout: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
